name: Push images to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
  REGION_NAME: ap-south-1
  ECS_TASK_DEFINITION: ./task-definition.json
  CONTAINER_NAME: node-ecs

jobs:
  deploy:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout code on push or workflow dispatch
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ROLE_TO_ASSUME }}:role/ecs-automate
          role-session-name: ecs-session
          aws-region: ${{ env.REGION_NAME }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
        # Safety measures but not expected 
        #
        # with:
        #   registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION_NAME }}.amazonaws.com
        #   username: docker_username_${{ secrets.DOCKER_USERNAME }}_dkr_ecr_aws_region_1_amazonaws_com
        #   password: docker_password_${{ secrets.DOCKER_PASS }}_dkr_ecr_aws_region_1_amazonaws_com
      - name: Get current date
        id: date
        run:  echo "::set-output name=date::$(date +'%d-%m-%y')"

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # ECR_REPOSITORY: ${{ secrets.ECR_REPO }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: node-ecs-gh
          IMAGE_TAG: node-ecs-gh-image-${{ github.run_number }}-${{ steps.date.outputs.date }}
          IMAGE_NAME: node-api-image-${{ steps.date.outputs.date }}
        run: |
          echo "Image Name: $IMAGE_NAME"
          echo "Image Tag: $IMAGE_TAG"
          echo "$ECR_REGISTRY"
          echo "$ECR_REPOSITORY"
          echo "docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./nodeJS"
          echo "docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./nodeJS
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Image Name: $IMAGE_NAME"
          echo "Image Tag: $IMAGE_TAG"
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }} 

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service:  my-service
          cluster:  node-ecs-cluster
          wait-for-service-stability: true

